// @generated by Peggy 4.0.2.
//
// https://peggyjs.org/



	var parse__boolean__1, parse__boolean__2, parse__identifier__1, parse__number__1, parse__string__1, parse__string__2;

	import {
	  undef,
	  nonEmpty
	} from '@jdeighan/llutils';

	import {
	  DUMP
	} from '@jdeighan/llutils/dump';

	// --------------------------------------------------------------
	parse__boolean__1 = () => {
	  return {
	    type: 'boolean',
	    value: true
	  };
	};

	// --------------------------------------------------------------
	parse__boolean__2 = () => {
	  return {
	    type: 'boolean',
	    value: false
	  };
	};

	// --------------------------------------------------------------
	parse__number__1 = (pre, post) => {
	  if (nonEmpty(post)) {
	    return {
	      type: "float",
	      value: parseFloat(`${pre}${post}`)
	    };
	  } else {
	    return {
	      type: "integer",
	      value: parseInt(pre, 10)
	    };
	  }
	};

	// --------------------------------------------------------------
	parse__string__1 = (str) => {
	  return {
	    type: 'string',
	    value: str
	  };
	};

	// --------------------------------------------------------------
	parse__string__2 = (str) => {
	  return {
	    type: 'string',
	    value: str
	  };
	};

	// --------------------------------------------------------------
	parse__identifier__1 = (str) => {
	  return {
	    type: 'identifier',
	    value: str
	  };
	};

function peg$subclass(child, parent) {
  function C() { this.constructor = child; }
  C.prototype = parent.prototype;
  child.prototype = new C();
}

function peg$SyntaxError(message, expected, found, location) {
  var self = Error.call(this, message);
  // istanbul ignore next Check is a necessary evil to support older environments
  if (Object.setPrototypeOf) {
    Object.setPrototypeOf(self, peg$SyntaxError.prototype);
  }
  self.expected = expected;
  self.found = found;
  self.location = location;
  self.name = "SyntaxError";
  return self;
}

peg$subclass(peg$SyntaxError, Error);

function peg$padEnd(str, targetLength, padString) {
  padString = padString || " ";
  if (str.length > targetLength) { return str; }
  targetLength -= str.length;
  padString += padString.repeat(targetLength);
  return str + padString.slice(0, targetLength);
}

peg$SyntaxError.prototype.format = function(sources) {
  var str = "Error: " + this.message;
  if (this.location) {
    var src = null;
    var k;
    for (k = 0; k < sources.length; k++) {
      if (sources[k].source === this.location.source) {
        src = sources[k].text.split(/\r\n|\n|\r/g);
        break;
      }
    }
    var s = this.location.start;
    var offset_s = (this.location.source && (typeof this.location.source.offset === "function"))
      ? this.location.source.offset(s)
      : s;
    var loc = this.location.source + ":" + offset_s.line + ":" + offset_s.column;
    if (src) {
      var e = this.location.end;
      var filler = peg$padEnd("", offset_s.line.toString().length, ' ');
      var line = src[s.line - 1];
      var last = s.line === e.line ? e.column : line.length + 1;
      var hatLen = (last - s.column) || 1;
      str += "\n --> " + loc + "\n"
          + filler + " |\n"
          + offset_s.line + " | " + line + "\n"
          + filler + " | " + peg$padEnd("", s.column - 1, ' ')
          + peg$padEnd("", hatLen, "^");
    } else {
      str += "\n at " + loc;
    }
  }
  return str;
};

peg$SyntaxError.buildMessage = function(expected, found) {
  var DESCRIBE_EXPECTATION_FNS = {
    literal: function(expectation) {
      return "\"" + literalEscape(expectation.text) + "\"";
    },

    class: function(expectation) {
      var escapedParts = expectation.parts.map(function(part) {
        return Array.isArray(part)
          ? classEscape(part[0]) + "-" + classEscape(part[1])
          : classEscape(part);
      });

      return "[" + (expectation.inverted ? "^" : "") + escapedParts.join("") + "]";
    },

    any: function() {
      return "any character";
    },

    end: function() {
      return "end of input";
    },

    other: function(expectation) {
      return expectation.description;
    }
  };

  function hex(ch) {
    return ch.charCodeAt(0).toString(16).toUpperCase();
  }

  function literalEscape(s) {
    return s
      .replace(/\\/g, "\\\\")
      .replace(/"/g,  "\\\"")
      .replace(/\0/g, "\\0")
      .replace(/\t/g, "\\t")
      .replace(/\n/g, "\\n")
      .replace(/\r/g, "\\r")
      .replace(/[\x00-\x0F]/g,          function(ch) { return "\\x0" + hex(ch); })
      .replace(/[\x10-\x1F\x7F-\x9F]/g, function(ch) { return "\\x"  + hex(ch); });
  }

  function classEscape(s) {
    return s
      .replace(/\\/g, "\\\\")
      .replace(/\]/g, "\\]")
      .replace(/\^/g, "\\^")
      .replace(/-/g,  "\\-")
      .replace(/\0/g, "\\0")
      .replace(/\t/g, "\\t")
      .replace(/\n/g, "\\n")
      .replace(/\r/g, "\\r")
      .replace(/[\x00-\x0F]/g,          function(ch) { return "\\x0" + hex(ch); })
      .replace(/[\x10-\x1F\x7F-\x9F]/g, function(ch) { return "\\x"  + hex(ch); });
  }

  function describeExpectation(expectation) {
    return DESCRIBE_EXPECTATION_FNS[expectation.type](expectation);
  }

  function describeExpected(expected) {
    var descriptions = expected.map(describeExpectation);
    var i, j;

    descriptions.sort();

    if (descriptions.length > 0) {
      for (i = 1, j = 1; i < descriptions.length; i++) {
        if (descriptions[i - 1] !== descriptions[i]) {
          descriptions[j] = descriptions[i];
          j++;
        }
      }
      descriptions.length = j;
    }

    switch (descriptions.length) {
      case 1:
        return descriptions[0];

      case 2:
        return descriptions[0] + " or " + descriptions[1];

      default:
        return descriptions.slice(0, -1).join(", ")
          + ", or "
          + descriptions[descriptions.length - 1];
    }
  }

  function describeFound(found) {
    return found ? "\"" + literalEscape(found) + "\"" : "end of input";
  }

  return "Expected " + describeExpected(expected) + " but " + describeFound(found) + " found.";
};

function peg$DefaultTracer() {
  this.indentLevel = 0;
}

peg$DefaultTracer.prototype.destroy = function() {};
peg$DefaultTracer.prototype.trace = function(event) {
  var that = this;

  function log(event) {
    function repeat(str, n) {
       var resultStr = "", i;

       for (i = 0; i < n; i++) {
         resultStr += str;
       }

       return resultStr;
    }

    function pad(string, length) {
      return string + repeat(" ", length - string.length);
    }

    if (typeof console === "object") {
      console.log(
        event.location.start.line + ":" + event.location.start.column + "-"
          + event.location.end.line + ":" + event.location.end.column + " "
          + pad(event.type, 12) + " "
          + repeat("  ", that.indentLevel)
          + (event.type.startsWith('rule') ? '<' + event.rule + '>' : '')
          + (event.result ? ' ' + JSON.stringify(event.result) : '')
      );
    }
  }

  switch (event.type) {
    case "rule.enter":
      log(event);
      this.indentLevel++;
      break;

    case "rule.match":
      this.indentLevel--;
      log(event);
      break;

    case "rule.fail":
      this.indentLevel--;
      log(event);
      break;

  }
};

function peg$parse(input, options) {
  options = options !== undefined ? options : {};

  var peg$FAILED = {};
  var peg$source = options.grammarSource;

  var peg$startRuleFunctions = { token: peg$parse_token, boolean: peg$parse_boolean, number: peg$parse_number, string: peg$parse_string, identifier: peg$parse_identifier, NL: peg$parse_NL, _: peg$parse__ };
  var peg$startRuleFunction = peg$parse_token;

  var peg$c0 = "true";
  var peg$c1 = "false";
  var peg$c2 = "pre";
  var peg$c3 = ".";
  var peg$c4 = "post";
  var peg$c5 = "\"";
  var peg$c6 = "str";
  var peg$c7 = "'";
  var peg$c8 = "\r";
  var peg$c9 = "\n";
  var peg$c10 = " ";
  var peg$r0 = /^[0-9]/;
  var peg$r1 = /^[^"]/;
  var peg$r2 = /^[^']/;
  var peg$r3 = /^[A-Za-z]/;
  var peg$e0 = peg$literalExpectation("true", false);
  var peg$e1 = peg$literalExpectation("false", false);
  var peg$e2 = peg$classExpectation([["0", "9"]], false, false);
  var peg$e3 = peg$literalExpectation(".", false);
  var peg$e4 = peg$literalExpectation("\"", false);
  var peg$e5 = peg$classExpectation(["\""], true, false);
  var peg$e6 = peg$literalExpectation("'", false);
  var peg$e7 = peg$classExpectation(["'"], true, false);
  var peg$e8 = peg$classExpectation([["A", "Z"], ["a", "z"]], false, false);
  var peg$e9 = peg$literalExpectation("\r", false);
  var peg$e10 = peg$literalExpectation("\n", false);
  var peg$e11 = peg$literalExpectation(" ", false);

  var peg$f0 = function() { return parse__boolean__1(); };
  var peg$f1 = function() { return parse__boolean__2(); };
  var peg$f2 = function(pre, post) { return parse__number__1(pre, post); };
  var peg$f3 = function(str) { return parse__string__1(str); };
  var peg$f4 = function(str) { return parse__string__2(str); };
  var peg$f5 = function(str) {return (str != 'if');};
  var peg$f6 = function(str) { return parse__identifier__1(str); };
  var peg$currPos = options.peg$currPos | 0;
  var peg$savedPos = peg$currPos;
  var peg$posDetailsCache = [{ line: 1, column: 1 }];
  var peg$maxFailPos = peg$currPos;
  var peg$maxFailExpected = options.peg$maxFailExpected || [];
  var peg$silentFails = options.peg$silentFails | 0;

  var peg$tracer = ("tracer" in options) && (options.tracer !== undefined)
    ? options.tracer
    : new peg$DefaultTracer();

  var peg$result;

  if (options.startRule) {
    if (!(options.startRule in peg$startRuleFunctions)) {
      throw new Error("Can't start parsing from rule \"" + options.startRule + "\".");
    }

    peg$startRuleFunction = peg$startRuleFunctions[options.startRule];
  }

  function text() {
    return input.substring(peg$savedPos, peg$currPos);
  }

  function offset() {
    return peg$savedPos;
  }

  function range() {
    return {
      source: peg$source,
      start: peg$savedPos,
      end: peg$currPos
    };
  }

  function location() {
    return peg$computeLocation(peg$savedPos, peg$currPos);
  }

  function expected(description, location) {
    location = location !== undefined
      ? location
      : peg$computeLocation(peg$savedPos, peg$currPos);

    throw peg$buildStructuredError(
      [peg$otherExpectation(description)],
      input.substring(peg$savedPos, peg$currPos),
      location
    );
  }

  function error(message, location) {
    location = location !== undefined
      ? location
      : peg$computeLocation(peg$savedPos, peg$currPos);

    throw peg$buildSimpleError(message, location);
  }

  function peg$literalExpectation(text, ignoreCase) {
    return { type: "literal", text: text, ignoreCase: ignoreCase };
  }

  function peg$classExpectation(parts, inverted, ignoreCase) {
    return { type: "class", parts: parts, inverted: inverted, ignoreCase: ignoreCase };
  }

  function peg$anyExpectation() {
    return { type: "any" };
  }

  function peg$endExpectation() {
    return { type: "end" };
  }

  function peg$otherExpectation(description) {
    return { type: "other", description: description };
  }

  function peg$computePosDetails(pos) {
    var details = peg$posDetailsCache[pos];
    var p;

    if (details) {
      return details;
    } else {
      if (pos >= peg$posDetailsCache.length) {
        p = peg$posDetailsCache.length - 1;
      } else {
        p = pos;
        while (!peg$posDetailsCache[--p]) {}
      }

      details = peg$posDetailsCache[p];
      details = {
        line: details.line,
        column: details.column
      };

      while (p < pos) {
        if (input.charCodeAt(p) === 10) {
          details.line++;
          details.column = 1;
        } else {
          details.column++;
        }

        p++;
      }

      peg$posDetailsCache[pos] = details;

      return details;
    }
  }

  function peg$computeLocation(startPos, endPos, offset) {
    var startPosDetails = peg$computePosDetails(startPos);
    var endPosDetails = peg$computePosDetails(endPos);

    var res = {
      source: peg$source,
      start: {
        offset: startPos,
        line: startPosDetails.line,
        column: startPosDetails.column
      },
      end: {
        offset: endPos,
        line: endPosDetails.line,
        column: endPosDetails.column
      }
    };
    if (offset && peg$source && (typeof peg$source.offset === "function")) {
      res.start = peg$source.offset(res.start);
      res.end = peg$source.offset(res.end);
    }
    return res;
  }

  function peg$fail(expected) {
    if (peg$currPos < peg$maxFailPos) { return; }

    if (peg$currPos > peg$maxFailPos) {
      peg$maxFailPos = peg$currPos;
      peg$maxFailExpected = [];
    }

    peg$maxFailExpected.push(expected);
  }

  function peg$buildSimpleError(message, location) {
    return new peg$SyntaxError(message, null, null, location);
  }

  function peg$buildStructuredError(expected, found, location) {
    return new peg$SyntaxError(
      peg$SyntaxError.buildMessage(expected, found),
      expected,
      found,
      location
    );
  }

  function peg$parse_token() {
    var startPos = peg$currPos;
    var s0;

    peg$tracer.trace({
      type: "rule.enter",
      rule: "token",
      location: peg$computeLocation(startPos, startPos, true),
    });

    s0 = peg$parse_boolean();
    if (s0 === peg$FAILED) {
      s0 = peg$parse_number();
      if (s0 === peg$FAILED) {
        s0 = peg$parse_string();
        if (s0 === peg$FAILED) {
          s0 = peg$parse_identifier();
          if (s0 === peg$FAILED) {
            s0 = peg$parse_NL();
          }
        }
      }
    }

    if (s0 !== peg$FAILED) {
      peg$tracer.trace({
        type: "rule.match",
        rule: "token",
        result: s0,
        location: peg$computeLocation(startPos, peg$currPos, true),
      });
    } else {
      peg$tracer.trace({
        type: "rule.fail",
        rule: "token",
        location: peg$computeLocation(startPos, startPos, true),
      });
    }

    return s0;
  }

  function peg$parse_boolean() {
    var startPos = peg$currPos;
    var s0, s1;

    peg$tracer.trace({
      type: "rule.enter",
      rule: "boolean",
      location: peg$computeLocation(startPos, startPos, true),
    });

    s0 = peg$currPos;
    if (input.substr(peg$currPos, 4) === peg$c0) {
      s1 = peg$c0;
      peg$currPos += 4;
      peg$tracer.trace({
        type: "string.match",
        rule: "boolean",
        result: "true",
        location: peg$computeLocation(startPos, peg$currPos, true),
      });
    } else {
      s1 = peg$FAILED;
      if (peg$silentFails === 0) { peg$fail(peg$e0); }
      peg$tracer.trace({
        type: "string.fail",
        rule: "boolean",
        details: "true",
        location: peg$computeLocation(peg$currPos, peg$currPos, true),
      });
    }
    if (s1 !== peg$FAILED) {
      peg$savedPos = s0;
      s1 = peg$f0();
    }
    s0 = s1;
    if (s0 === peg$FAILED) {
      s0 = peg$currPos;
      if (input.substr(peg$currPos, 5) === peg$c1) {
        s1 = peg$c1;
        peg$currPos += 5;
        peg$tracer.trace({
          type: "string.match",
          rule: "boolean",
          result: "false",
          location: peg$computeLocation(startPos, peg$currPos, true),
        });
      } else {
        s1 = peg$FAILED;
        if (peg$silentFails === 0) { peg$fail(peg$e1); }
        peg$tracer.trace({
          type: "string.fail",
          rule: "boolean",
          details: "false",
          location: peg$computeLocation(peg$currPos, peg$currPos, true),
        });
      }
      if (s1 !== peg$FAILED) {
        peg$savedPos = s0;
        s1 = peg$f1();
      }
      s0 = s1;
    }

    if (s0 !== peg$FAILED) {
      peg$tracer.trace({
        type: "rule.match",
        rule: "boolean",
        result: s0,
        location: peg$computeLocation(startPos, peg$currPos, true),
      });
    } else {
      peg$tracer.trace({
        type: "rule.fail",
        rule: "boolean",
        location: peg$computeLocation(startPos, startPos, true),
      });
    }

    return s0;
  }

  function peg$parse_number() {
    var startPos = peg$currPos;
    var s0, s1, s2, s3, s4, s5, s6;

    peg$tracer.trace({
      type: "rule.enter",
      rule: "number",
      location: peg$computeLocation(startPos, startPos, true),
    });

    s0 = peg$currPos;
    s1 = peg$currPos;
    s2 = [];
    s3 = input.charAt(peg$currPos);
    if (peg$r0.test(s3)) {
      peg$currPos++;
      peg$tracer.trace({
        type: "class.match",
        rule: "number",
        result: input.charAt(peg$currPos-1),
        details: peg$r0.toString(),
        location: peg$computeLocation(peg$currPos-1, peg$currPos, true),
      });
    } else {
      s3 = peg$FAILED;
      if (peg$silentFails === 0) { peg$fail(peg$e2); }
      peg$tracer.trace({
        type: "class.fail",
        rule: "number",
        details: peg$r0.toString(),
        location: peg$computeLocation(peg$currPos, peg$currPos, true),
      });
    }
    if (s3 !== peg$FAILED) {
      while (s3 !== peg$FAILED) {
        s2.push(s3);
        s3 = input.charAt(peg$currPos);
        if (peg$r0.test(s3)) {
          peg$currPos++;
          peg$tracer.trace({
            type: "class.match",
            rule: "number",
            result: input.charAt(peg$currPos-1),
            details: peg$r0.toString(),
            location: peg$computeLocation(peg$currPos-1, peg$currPos, true),
          });
        } else {
          s3 = peg$FAILED;
          if (peg$silentFails === 0) { peg$fail(peg$e2); }
          peg$tracer.trace({
            type: "class.fail",
            rule: "number",
            details: peg$r0.toString(),
            location: peg$computeLocation(peg$currPos, peg$currPos, true),
          });
        }
      }
    } else {
      s2 = peg$FAILED;
    }
    if (s2 !== peg$FAILED) {
      s1 = input.substring(s1, peg$currPos);
    } else {
      s1 = s2;
    }
    if (s1 !== peg$FAILED) {
      s2 = peg$currPos;
      s3 = peg$currPos;
      if (input.charCodeAt(peg$currPos) === 46) {
        s4 = peg$c3;
        peg$currPos++;
        peg$tracer.trace({
          type: "string.match",
          rule: "number",
          result: ".",
          location: peg$computeLocation(startPos, peg$currPos, true),
        });
      } else {
        s4 = peg$FAILED;
        if (peg$silentFails === 0) { peg$fail(peg$e3); }
        peg$tracer.trace({
          type: "string.fail",
          rule: "number",
          details: ".",
          location: peg$computeLocation(peg$currPos, peg$currPos, true),
        });
      }
      if (s4 !== peg$FAILED) {
        s5 = [];
        s6 = input.charAt(peg$currPos);
        if (peg$r0.test(s6)) {
          peg$currPos++;
          peg$tracer.trace({
            type: "class.match",
            rule: "number",
            result: input.charAt(peg$currPos-1),
            details: peg$r0.toString(),
            location: peg$computeLocation(peg$currPos-1, peg$currPos, true),
          });
        } else {
          s6 = peg$FAILED;
          if (peg$silentFails === 0) { peg$fail(peg$e2); }
          peg$tracer.trace({
            type: "class.fail",
            rule: "number",
            details: peg$r0.toString(),
            location: peg$computeLocation(peg$currPos, peg$currPos, true),
          });
        }
        while (s6 !== peg$FAILED) {
          s5.push(s6);
          s6 = input.charAt(peg$currPos);
          if (peg$r0.test(s6)) {
            peg$currPos++;
            peg$tracer.trace({
              type: "class.match",
              rule: "number",
              result: input.charAt(peg$currPos-1),
              details: peg$r0.toString(),
              location: peg$computeLocation(peg$currPos-1, peg$currPos, true),
            });
          } else {
            s6 = peg$FAILED;
            if (peg$silentFails === 0) { peg$fail(peg$e2); }
            peg$tracer.trace({
              type: "class.fail",
              rule: "number",
              details: peg$r0.toString(),
              location: peg$computeLocation(peg$currPos, peg$currPos, true),
            });
          }
        }
        s4 = [s4, s5];
        s3 = s4;
      } else {
        peg$currPos = s3;
        s3 = peg$FAILED;
      }
      if (s3 === peg$FAILED) {
        s3 = null;
      }
      s2 = input.substring(s2, peg$currPos);
      peg$savedPos = s0;
      s0 = peg$f2(s1, s2);
    } else {
      peg$currPos = s0;
      s0 = peg$FAILED;
    }

    if (s0 !== peg$FAILED) {
      peg$tracer.trace({
        type: "rule.match",
        rule: "number",
        result: s0,
        location: peg$computeLocation(startPos, peg$currPos, true),
      });
    } else {
      peg$tracer.trace({
        type: "rule.fail",
        rule: "number",
        location: peg$computeLocation(startPos, startPos, true),
      });
    }

    return s0;
  }

  function peg$parse_string() {
    var startPos = peg$currPos;
    var s0, s1, s2, s3, s4;

    peg$tracer.trace({
      type: "rule.enter",
      rule: "string",
      location: peg$computeLocation(startPos, startPos, true),
    });

    s0 = peg$currPos;
    if (input.charCodeAt(peg$currPos) === 34) {
      s1 = peg$c5;
      peg$currPos++;
      peg$tracer.trace({
        type: "string.match",
        rule: "string",
        result: "\"",
        location: peg$computeLocation(startPos, peg$currPos, true),
      });
    } else {
      s1 = peg$FAILED;
      if (peg$silentFails === 0) { peg$fail(peg$e4); }
      peg$tracer.trace({
        type: "string.fail",
        rule: "string",
        details: "\"",
        location: peg$computeLocation(peg$currPos, peg$currPos, true),
      });
    }
    if (s1 !== peg$FAILED) {
      s2 = peg$currPos;
      s3 = [];
      s4 = input.charAt(peg$currPos);
      if (peg$r1.test(s4)) {
        peg$currPos++;
        peg$tracer.trace({
          type: "class.match",
          rule: "string",
          result: input.charAt(peg$currPos-1),
          details: peg$r1.toString(),
          location: peg$computeLocation(peg$currPos-1, peg$currPos, true),
        });
      } else {
        s4 = peg$FAILED;
        if (peg$silentFails === 0) { peg$fail(peg$e5); }
        peg$tracer.trace({
          type: "class.fail",
          rule: "string",
          details: peg$r1.toString(),
          location: peg$computeLocation(peg$currPos, peg$currPos, true),
        });
      }
      while (s4 !== peg$FAILED) {
        s3.push(s4);
        s4 = input.charAt(peg$currPos);
        if (peg$r1.test(s4)) {
          peg$currPos++;
          peg$tracer.trace({
            type: "class.match",
            rule: "string",
            result: input.charAt(peg$currPos-1),
            details: peg$r1.toString(),
            location: peg$computeLocation(peg$currPos-1, peg$currPos, true),
          });
        } else {
          s4 = peg$FAILED;
          if (peg$silentFails === 0) { peg$fail(peg$e5); }
          peg$tracer.trace({
            type: "class.fail",
            rule: "string",
            details: peg$r1.toString(),
            location: peg$computeLocation(peg$currPos, peg$currPos, true),
          });
        }
      }
      s2 = input.substring(s2, peg$currPos);
      if (input.charCodeAt(peg$currPos) === 34) {
        s3 = peg$c5;
        peg$currPos++;
        peg$tracer.trace({
          type: "string.match",
          rule: "string",
          result: "\"",
          location: peg$computeLocation(startPos, peg$currPos, true),
        });
      } else {
        s3 = peg$FAILED;
        if (peg$silentFails === 0) { peg$fail(peg$e4); }
        peg$tracer.trace({
          type: "string.fail",
          rule: "string",
          details: "\"",
          location: peg$computeLocation(peg$currPos, peg$currPos, true),
        });
      }
      if (s3 !== peg$FAILED) {
        peg$savedPos = s0;
        s0 = peg$f3(s2);
      } else {
        peg$currPos = s0;
        s0 = peg$FAILED;
      }
    } else {
      peg$currPos = s0;
      s0 = peg$FAILED;
    }
    if (s0 === peg$FAILED) {
      s0 = peg$currPos;
      if (input.charCodeAt(peg$currPos) === 39) {
        s1 = peg$c7;
        peg$currPos++;
        peg$tracer.trace({
          type: "string.match",
          rule: "string",
          result: "'",
          location: peg$computeLocation(startPos, peg$currPos, true),
        });
      } else {
        s1 = peg$FAILED;
        if (peg$silentFails === 0) { peg$fail(peg$e6); }
        peg$tracer.trace({
          type: "string.fail",
          rule: "string",
          details: "'",
          location: peg$computeLocation(peg$currPos, peg$currPos, true),
        });
      }
      if (s1 !== peg$FAILED) {
        s2 = peg$currPos;
        s3 = [];
        s4 = input.charAt(peg$currPos);
        if (peg$r2.test(s4)) {
          peg$currPos++;
          peg$tracer.trace({
            type: "class.match",
            rule: "string",
            result: input.charAt(peg$currPos-1),
            details: peg$r2.toString(),
            location: peg$computeLocation(peg$currPos-1, peg$currPos, true),
          });
        } else {
          s4 = peg$FAILED;
          if (peg$silentFails === 0) { peg$fail(peg$e7); }
          peg$tracer.trace({
            type: "class.fail",
            rule: "string",
            details: peg$r2.toString(),
            location: peg$computeLocation(peg$currPos, peg$currPos, true),
          });
        }
        while (s4 !== peg$FAILED) {
          s3.push(s4);
          s4 = input.charAt(peg$currPos);
          if (peg$r2.test(s4)) {
            peg$currPos++;
            peg$tracer.trace({
              type: "class.match",
              rule: "string",
              result: input.charAt(peg$currPos-1),
              details: peg$r2.toString(),
              location: peg$computeLocation(peg$currPos-1, peg$currPos, true),
            });
          } else {
            s4 = peg$FAILED;
            if (peg$silentFails === 0) { peg$fail(peg$e7); }
            peg$tracer.trace({
              type: "class.fail",
              rule: "string",
              details: peg$r2.toString(),
              location: peg$computeLocation(peg$currPos, peg$currPos, true),
            });
          }
        }
        s2 = input.substring(s2, peg$currPos);
        if (input.charCodeAt(peg$currPos) === 39) {
          s3 = peg$c7;
          peg$currPos++;
          peg$tracer.trace({
            type: "string.match",
            rule: "string",
            result: "'",
            location: peg$computeLocation(startPos, peg$currPos, true),
          });
        } else {
          s3 = peg$FAILED;
          if (peg$silentFails === 0) { peg$fail(peg$e6); }
          peg$tracer.trace({
            type: "string.fail",
            rule: "string",
            details: "'",
            location: peg$computeLocation(peg$currPos, peg$currPos, true),
          });
        }
        if (s3 !== peg$FAILED) {
          peg$savedPos = s0;
          s0 = peg$f4(s2);
        } else {
          peg$currPos = s0;
          s0 = peg$FAILED;
        }
      } else {
        peg$currPos = s0;
        s0 = peg$FAILED;
      }
    }

    if (s0 !== peg$FAILED) {
      peg$tracer.trace({
        type: "rule.match",
        rule: "string",
        result: s0,
        location: peg$computeLocation(startPos, peg$currPos, true),
      });
    } else {
      peg$tracer.trace({
        type: "rule.fail",
        rule: "string",
        location: peg$computeLocation(startPos, startPos, true),
      });
    }

    return s0;
  }

  function peg$parse_identifier() {
    var startPos = peg$currPos;
    var s0, s1, s2, s3;

    peg$tracer.trace({
      type: "rule.enter",
      rule: "identifier",
      location: peg$computeLocation(startPos, startPos, true),
    });

    s0 = peg$currPos;
    s1 = peg$currPos;
    s2 = [];
    s3 = input.charAt(peg$currPos);
    if (peg$r3.test(s3)) {
      peg$currPos++;
      peg$tracer.trace({
        type: "class.match",
        rule: "identifier",
        result: input.charAt(peg$currPos-1),
        details: peg$r3.toString(),
        location: peg$computeLocation(peg$currPos-1, peg$currPos, true),
      });
    } else {
      s3 = peg$FAILED;
      if (peg$silentFails === 0) { peg$fail(peg$e8); }
      peg$tracer.trace({
        type: "class.fail",
        rule: "identifier",
        details: peg$r3.toString(),
        location: peg$computeLocation(peg$currPos, peg$currPos, true),
      });
    }
    if (s3 !== peg$FAILED) {
      while (s3 !== peg$FAILED) {
        s2.push(s3);
        s3 = input.charAt(peg$currPos);
        if (peg$r3.test(s3)) {
          peg$currPos++;
          peg$tracer.trace({
            type: "class.match",
            rule: "identifier",
            result: input.charAt(peg$currPos-1),
            details: peg$r3.toString(),
            location: peg$computeLocation(peg$currPos-1, peg$currPos, true),
          });
        } else {
          s3 = peg$FAILED;
          if (peg$silentFails === 0) { peg$fail(peg$e8); }
          peg$tracer.trace({
            type: "class.fail",
            rule: "identifier",
            details: peg$r3.toString(),
            location: peg$computeLocation(peg$currPos, peg$currPos, true),
          });
        }
      }
    } else {
      s2 = peg$FAILED;
    }
    if (s2 !== peg$FAILED) {
      s1 = input.substring(s1, peg$currPos);
    } else {
      s1 = s2;
    }
    if (s1 !== peg$FAILED) {
      peg$savedPos = peg$currPos;
      s2 = peg$f5(s1);
      if (s2) {
        s2 = undefined;
      } else {
        s2 = peg$FAILED;
      }
      if (s2 !== peg$FAILED) {
        peg$savedPos = s0;
        s0 = peg$f6(s1);
      } else {
        peg$currPos = s0;
        s0 = peg$FAILED;
      }
    } else {
      peg$currPos = s0;
      s0 = peg$FAILED;
    }

    if (s0 !== peg$FAILED) {
      peg$tracer.trace({
        type: "rule.match",
        rule: "identifier",
        result: s0,
        location: peg$computeLocation(startPos, peg$currPos, true),
      });
    } else {
      peg$tracer.trace({
        type: "rule.fail",
        rule: "identifier",
        location: peg$computeLocation(startPos, startPos, true),
      });
    }

    return s0;
  }

  function peg$parse_NL() {
    var startPos = peg$currPos;
    var s0, s1, s2;

    peg$tracer.trace({
      type: "rule.enter",
      rule: "NL",
      location: peg$computeLocation(startPos, startPos, true),
    });

    s0 = peg$currPos;
    if (input.charCodeAt(peg$currPos) === 13) {
      s1 = peg$c8;
      peg$currPos++;
      peg$tracer.trace({
        type: "string.match",
        rule: "NL",
        result: "\r",
        location: peg$computeLocation(startPos, peg$currPos, true),
      });
    } else {
      s1 = peg$FAILED;
      if (peg$silentFails === 0) { peg$fail(peg$e9); }
      peg$tracer.trace({
        type: "string.fail",
        rule: "NL",
        details: "\r",
        location: peg$computeLocation(peg$currPos, peg$currPos, true),
      });
    }
    if (s1 === peg$FAILED) {
      s1 = null;
    }
    if (input.charCodeAt(peg$currPos) === 10) {
      s2 = peg$c9;
      peg$currPos++;
      peg$tracer.trace({
        type: "string.match",
        rule: "NL",
        result: "\n",
        location: peg$computeLocation(startPos, peg$currPos, true),
      });
    } else {
      s2 = peg$FAILED;
      if (peg$silentFails === 0) { peg$fail(peg$e10); }
      peg$tracer.trace({
        type: "string.fail",
        rule: "NL",
        details: "\n",
        location: peg$computeLocation(peg$currPos, peg$currPos, true),
      });
    }
    if (s2 !== peg$FAILED) {
      s1 = [s1, s2];
      s0 = s1;
    } else {
      peg$currPos = s0;
      s0 = peg$FAILED;
    }

    if (s0 !== peg$FAILED) {
      peg$tracer.trace({
        type: "rule.match",
        rule: "NL",
        result: s0,
        location: peg$computeLocation(startPos, peg$currPos, true),
      });
    } else {
      peg$tracer.trace({
        type: "rule.fail",
        rule: "NL",
        location: peg$computeLocation(startPos, startPos, true),
      });
    }

    return s0;
  }

  function peg$parse__() {
    var startPos = peg$currPos;
    var s0, s1;

    peg$tracer.trace({
      type: "rule.enter",
      rule: "_",
      location: peg$computeLocation(startPos, startPos, true),
    });

    s0 = [];
    if (input.charCodeAt(peg$currPos) === 32) {
      s1 = peg$c10;
      peg$currPos++;
      peg$tracer.trace({
        type: "string.match",
        rule: "_",
        result: " ",
        location: peg$computeLocation(startPos, peg$currPos, true),
      });
    } else {
      s1 = peg$FAILED;
      if (peg$silentFails === 0) { peg$fail(peg$e11); }
      peg$tracer.trace({
        type: "string.fail",
        rule: "_",
        details: " ",
        location: peg$computeLocation(peg$currPos, peg$currPos, true),
      });
    }
    if (s1 !== peg$FAILED) {
      while (s1 !== peg$FAILED) {
        s0.push(s1);
        if (input.charCodeAt(peg$currPos) === 32) {
          s1 = peg$c10;
          peg$currPos++;
          peg$tracer.trace({
            type: "string.match",
            rule: "_",
            result: " ",
            location: peg$computeLocation(startPos, peg$currPos, true),
          });
        } else {
          s1 = peg$FAILED;
          if (peg$silentFails === 0) { peg$fail(peg$e11); }
          peg$tracer.trace({
            type: "string.fail",
            rule: "_",
            details: " ",
            location: peg$computeLocation(peg$currPos, peg$currPos, true),
          });
        }
      }
    } else {
      s0 = peg$FAILED;
    }

    if (s0 !== peg$FAILED) {
      peg$tracer.trace({
        type: "rule.match",
        rule: "_",
        result: s0,
        location: peg$computeLocation(startPos, peg$currPos, true),
      });
    } else {
      peg$tracer.trace({
        type: "rule.fail",
        rule: "_",
        location: peg$computeLocation(startPos, startPos, true),
      });
    }

    return s0;
  }

  peg$result = peg$startRuleFunction();

  if (options.peg$library) {
    return /** @type {any} */ ({
      peg$result,
      peg$currPos,
      peg$FAILED,
      peg$maxFailExpected,
      peg$maxFailPos
    });
  }
  peg$tracer.destroy();
  if (peg$result !== peg$FAILED && peg$currPos === input.length) {
    return peg$result;
  } else {
    if (peg$result !== peg$FAILED && peg$currPos < input.length) {
      peg$fail(peg$endExpectation());
    }

    throw peg$buildStructuredError(
      peg$maxFailExpected,
      peg$maxFailPos < input.length ? input.charAt(peg$maxFailPos) : null,
      peg$maxFailPos < input.length
        ? peg$computeLocation(peg$maxFailPos, peg$maxFailPos + 1)
        : peg$computeLocation(peg$maxFailPos, peg$maxFailPos)
    );
  }
}

const peg$allowedStartRules = [
  "token",
  "boolean",
  "number",
  "string",
  "identifier",
  "NL",
  "_"
];

export {
  peg$DefaultTracer as DefaultTracer,
  peg$allowedStartRules as StartRules,
  peg$SyntaxError as SyntaxError,
  peg$parse as parse
};
